// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[_id]/index.tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/addProduct/index.tsx";
import * as $4 from "./routes/api/file-stream.ts";
import * as $5 from "./routes/api/products/[id].ts";
import * as $6 from "./routes/api/profileReview/post.ts";
import * as $7 from "./routes/api/reviews/post.ts";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/products/index.tsx";
import * as $10 from "./routes/users/[_id].tsx";
import * as $11 from "./routes/users/index.tsx";
import * as $$0 from "./islands/ProfilePage.tsx";
import * as $$1 from "./islands/SingleProduct.tsx";
import * as $$2 from "./islands/Users.tsx";

const manifest = {
  routes: {
    "./routes/[_id]/index.tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/addProduct/index.tsx": $3,
    "./routes/api/file-stream.ts": $4,
    "./routes/api/products/[id].ts": $5,
    "./routes/api/profileReview/post.ts": $6,
    "./routes/api/reviews/post.ts": $7,
    "./routes/index.tsx": $8,
    "./routes/products/index.tsx": $9,
    "./routes/users/[_id].tsx": $10,
    "./routes/users/index.tsx": $11,
  },
  islands: {
    "./islands/ProfilePage.tsx": $$0,
    "./islands/SingleProduct.tsx": $$1,
    "./islands/Users.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
